/*
	Mixer Plus
	Header

	Author: John Peloquin
	Date: 2007
	Dependencies: windows.h, tchar.h
*/

/* Preprocessor */
#define MMERROR(x) (((MMRESULT)(x))!=MMSYSERR_NOERROR)
#define LENGTHOF(x) (sizeof(x)/sizeof(x[0]))

#define MIXERPLUS_WINDOW_CLASS				TEXT("MixerPlusWndCls")
#define MIXERPLUS_WINDOW_STYLE				WS_OVERLAPPED \
												| WS_CAPTION \
												| WS_SYSMENU \
												| WS_MINIMIZEBOX \
												| WS_HSCROLL

#define MIXERPLUS_MAX_TITLE					64 + MAXPNAMELEN

#define MIXERPLUS_LINE_CONTROL_VOLUME		0x0000001
#define MIXERPLUS_LINE_CONTROL_MUTE			0x0000002
#define MIXERPLUS_LINE_CONTROL_FEED			0x0000004

#define MIXERPLUS_LINES_PER_VIEW			5
#define MIXERPLUS_LINE_VOLUME_MAX			100
#define MIXERPLUS_LINE_VOLUME_MIN			0
#define MIXERPLUS_LINE_VOLUME_STEP			1
#define MIXERPLUS_LINE_VOLUME_PAGE			10
#define MIXERPLUS_LINE_FADER_PERIOD			20
#define MIXERPLUS_LINE_FADER_TIMER			WM_USER + 100

/* Datatypes */
typedef enum _MIXERPLUS_MODE
{
	MIXERPLUS_MODE_INVALID = 0,
	MIXERPLUS_MODE_PLAYBACK,
	MIXERPLUS_MODE_RECORDING

} MIXERPLUS_MODE, * PMIXERPLUS_MODE;

typedef enum _MIXERPLUS_LINE_FADER_MODE
{
	MIXERPLUS_LINE_FADER_MODE_NONE = 0,
	MIXERPLUS_LINE_FADER_MODE_IN,
	MIXERPLUS_LINE_FADER_MODE_OUT,
	MIXERPLUS_LINE_FADER_MODE_CROSS

} MIXERPLUS_LINE_FADER_MODE, * PMIXERPLUS_LINE_FADER_MODE;

typedef struct _MIXERPLUS_INFO
{
	MIXERPLUS_MODE mode;
	HINSTANCE hInstance;
	HANDLE hHeap;
	DWORD dwMixerID;

} MIXERPLUS_INFO, * PMIXERPLUS_INFO;

typedef struct _MIXERPLUS_CONTROL_FEED
{
	DWORD dwID;
	DWORD dwSources;
	LPMIXERCONTROLDETAILS_LISTTEXT pmxcdtls_lt;
	LPMIXERCONTROLDETAILS_BOOLEAN pmxcdtls_b;

} MIXERPLUS_CONTROL_FEED, * PMIXERPLUS_CONTROL_FEED;

typedef struct _MIXERPLUS_CONTROL_VOLUME
{
	DWORD dwID;
	BOOL bUniform;
	DWORD dwMin;
	DWORD dwMax;
	LPMIXERCONTROLDETAILS_UNSIGNED pmxcdtls_u;

} MIXERPLUS_CONTROL_VOLUME, * PMIXERPLUS_CONTROL_VOLUME;

typedef struct _MIXERPLUS_CONTROL_MUTE
{
	DWORD dwID;

} MIXERPLUS_CONTROL_MUTE, * PMIXERPLUS_CONTROL_MUTE;

typedef struct _MIXERPLUS_LINE_INFO
{
	MIXERPLUS_MODE mode;
	HANDLE hHeap;
	HMIXER hMixer;
	DWORD dwLineID;
	DWORD dwChannels;
	DWORD dwControlFlags;
	MIXERPLUS_CONTROL_VOLUME volume;
	MIXERPLUS_CONTROL_MUTE mute;
	MIXERPLUS_LINE_FADER_MODE fmode;
	HWND hCtrl;
	TCHAR szName[MIXER_LONG_NAME_CHARS];

} MIXERPLUS_LINE_INFO, * PMIXERPLUS_LINE_INFO;

/* Functions */
VOID MixerPlus_ErrorBox(HWND, LPCTSTR);
LRESULT CALLBACK MixerPlus_MainWndProc(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK MixerPlus_CtrlDlgProc(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK MixerPlus_CFaderDlgProc(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK MixerPlus_OptionsDlgProc(HWND, UINT, WPARAM, LPARAM);
